---
- name: Get vector distrib for RedHat-based systems
  ansible.builtin.get_url:
    url: https://packages.timber.io/vector/{{ vector_version }}/vector-{{ vector_version }}-1.x86_64.rpm
    dest: ./vector-{{ vector_version }}-1.x86_64.rpm
    mode: "0600"
  when: ansible_facts['os_family'] == "RedHat"

- name: Get vector distrib for Debian-based systems
  ansible.builtin.get_url:
    url: https://packages.timber.io/vector/{{ vector_version }}/vector_{{ vector_version }}-1_amd64.deb
    dest: ./vector_{{ vector_version }}-1_amd64.deb
    mode: "0600"
  when: ansible_facts['os_family'] == "Debian"

- name: Install Vector for RedHat-based systems
  become: true
  ansible.builtin.dnf:
    name: ./vector-{{ vector_version }}-1.x86_64.rpm
    disable_gpg_check: true
  when: ansible_facts['os_family'] == "RedHat"


- name: Install Vector for Debian-based systems
  become: true
  ansible.builtin.apt:
    deb: ./vector_{{ vector_version }}-1_amd64.deb
  when: ansible_facts['os_family'] == "Debian"

- name: Configuration Vector
  become: true
  ansible.builtin.template:
    src: ./vector.yaml.j2
    dest: /etc/vector/vector.yaml
    mode: "0644"
  notify: Restart vector service
